# Form implementation generated from reading ui file 'ninukiGui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 818)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Form)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.blackScoreLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.blackScoreLabel.setFont(font)
        self.blackScoreLabel.setObjectName("blackScoreLabel")
        self.verticalLayout.addWidget(self.blackScoreLabel)
        self.whiteScoreLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.whiteScoreLabel.setFont(font)
        self.whiteScoreLabel.setObjectName("whiteScoreLabel")
        self.verticalLayout.addWidget(self.whiteScoreLabel)
        self.currentPlayerLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.currentPlayerLabel.setFont(font)
        self.currentPlayerLabel.setObjectName("currentPlayerLabel")
        self.verticalLayout.addWidget(self.currentPlayerLabel)
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newGameButton = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.newGameButton.setFont(font)
        self.newGameButton.setObjectName("newGameButton")
        self.horizontalLayout_2.addWidget(self.newGameButton)
        self.predictButton = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.predictButton.setFont(font)
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout_2.addWidget(self.predictButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.blackScoreLabel.setText(_translate("Form", "Black Score:"))
        self.whiteScoreLabel.setText(_translate("Form", "White Score"))
        self.currentPlayerLabel.setText(_translate("Form", "Current Player:"))
        self.newGameButton.setText(_translate("Form", "New Game"))
        self.predictButton.setText(_translate("Form", "Predict"))
